// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>HLGranite.Nisan</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace HLGranite.Nisan
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    public partial class Customer : User
    {
    }

    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Agent))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Customer))]
    public partial class User : DatabaseObject
    {

        private Address addressField;

        private string nameField;

        private string passwodField;

        private string emailField;

        private string phoneField;

        public User()
        {
            this.addressField = new Address();
        }

        public Address Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }

        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        public string Passwod
        {
            get
            {
                return this.passwodField;
            }
            set
            {
                this.passwodField = value;
            }
        }

        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }

        public string Phone
        {
            get
            {
                return this.phoneField;
            }
            set
            {
                this.phoneField = value;
            }
        }
    }

    public partial class Address
    {

        private State stateField;

        private string streetField;

        private string postalField;

        public Address()
        {
            this.stateField = new State();
        }

        public State State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }

        public string Street
        {
            get
            {
                return this.streetField;
            }
            set
            {
                this.streetField = value;
            }
        }

        public string Postal
        {
            get
            {
                return this.postalField;
            }
            set
            {
                this.postalField = value;
            }
        }
    }

    public partial class State
    {

        private string nameField;

        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransactionItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Delivery))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Commission))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Payment))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Order))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Transaction))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Stock))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Nisan))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(User))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Agent))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Customer))]
    public partial class DatabaseObject
    {

        private string idField;

        private string tableNameField;

        private string remarksField;

        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        public string tableName
        {
            get
            {
                return this.tableNameField;
            }
            set
            {
                this.tableNameField = value;
            }
        }

        public string Remarks
        {
            get
            {
                return this.remarksField;
            }
            set
            {
                this.remarksField = value;
            }
        }
    }

    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Delivery))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Commission))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Payment))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Order))]
    public partial class TransactionItem : DatabaseObject
    {

        private Stock stockField;

        private string parentField;

        public TransactionItem()
        {
            this.stockField = new Stock();
        }

        public Stock Stock
        {
            get
            {
                return this.stockField;
            }
            set
            {
                this.stockField = value;
            }
        }

        public string Parent
        {
            get
            {
                return this.parentField;
            }
            set
            {
                this.parentField = value;
            }
        }
    }

    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Nisan))]
    public partial class Stock : DatabaseObject
    {

        private string typeField;

        private decimal priceField;

        private bool priceFieldSpecified;

        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        public decimal Price
        {
            get
            {
                return this.priceField;
            }
            set
            {
                this.priceField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PriceSpecified
        {
            get
            {
                return this.priceFieldSpecified;
            }
            set
            {
                this.priceFieldSpecified = value;
            }
        }
    }

    public partial class Nisan : Stock
    {

        private string nameField;

        private string jawiField;

        private System.DateTime bornField;

        private bool bornFieldSpecified;

        private System.DateTime deathField;

        private bool deathFieldSpecified;

        private System.DateTime deathmField;

        private bool deathmFieldSpecified;

        private string ageField;

        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        public string Jawi
        {
            get
            {
                return this.jawiField;
            }
            set
            {
                this.jawiField = value;
            }
        }

        public System.DateTime Born
        {
            get
            {
                return this.bornField;
            }
            set
            {
                this.bornField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BornSpecified
        {
            get
            {
                return this.bornFieldSpecified;
            }
            set
            {
                this.bornFieldSpecified = value;
            }
        }

        public System.DateTime Death
        {
            get
            {
                return this.deathField;
            }
            set
            {
                this.deathField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeathSpecified
        {
            get
            {
                return this.deathFieldSpecified;
            }
            set
            {
                this.deathFieldSpecified = value;
            }
        }

        public System.DateTime Deathm
        {
            get
            {
                return this.deathmField;
            }
            set
            {
                this.deathmField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeathmSpecified
        {
            get
            {
                return this.deathmFieldSpecified;
            }
            set
            {
                this.deathmFieldSpecified = value;
            }
        }

        public string Age
        {
            get
            {
                return this.ageField;
            }
            set
            {
                this.ageField = value;
            }
        }
    }

    public partial class Delivery : TransactionItem
    {
    }

    public partial class Commission : TransactionItem
    {
    }

    public partial class Payment : TransactionItem
    {
    }

    public partial class Order : TransactionItem
    {

        private Address shipToField;

        private Agent agentField;

        private string quantityField;

        private TransactionStage statusField;

        private bool statusFieldSpecified;

        public Order()
        {
            this.agentField = new Agent();
            this.shipToField = new Address();
        }

        public Address ShipTo
        {
            get
            {
                return this.shipToField;
            }
            set
            {
                this.shipToField = value;
            }
        }

        public Agent Agent
        {
            get
            {
                return this.agentField;
            }
            set
            {
                this.agentField = value;
            }
        }

        public string Quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }

        public TransactionStage Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusSpecified
        {
            get
            {
                return this.statusFieldSpecified;
            }
            set
            {
                this.statusFieldSpecified = value;
            }
        }
    }

    public partial class Agent : User
    {

        private Agent parentField;

        private string codeField;

        public Agent()
        {
            this.parentField = new Agent();
        }

        public Agent Parent
        {
            get
            {
                return this.parentField;
            }
            set
            {
                this.parentField = value;
            }
        }

        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
    }

    public enum TransactionStage
    {

        /// <remarks/>
        Draft,

        /// <remarks/>
        Confirmed,

        /// <remarks/>
        Paid,

        /// <remarks/>
        WorkInProgress,

        /// <remarks/>
        Delivering,

        /// <remarks/>
        Received,
    }

    public partial class Transaction : DatabaseObject
    {

        private List<TransactionItem> itemsField;

        private User createdByField;

        private TransactionType typeField;

        private bool typeFieldSpecified;

        private System.DateTime createdAtField;

        private bool createdAtFieldSpecified;

        private string noField;

        private string refrenceField;

        private decimal amountField;

        private bool amountFieldSpecified;

        public Transaction()
        {
            this.createdByField = new User();
            this.itemsField = new List<TransactionItem>();
        }

        public List<TransactionItem> Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        public User CreatedBy
        {
            get
            {
                return this.createdByField;
            }
            set
            {
                this.createdByField = value;
            }
        }

        public TransactionType Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypeSpecified
        {
            get
            {
                return this.typeFieldSpecified;
            }
            set
            {
                this.typeFieldSpecified = value;
            }
        }

        public System.DateTime CreatedAt
        {
            get
            {
                return this.createdAtField;
            }
            set
            {
                this.createdAtField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CreatedAtSpecified
        {
            get
            {
                return this.createdAtFieldSpecified;
            }
            set
            {
                this.createdAtFieldSpecified = value;
            }
        }

        public string No
        {
            get
            {
                return this.noField;
            }
            set
            {
                this.noField = value;
            }
        }

        public string Refrence
        {
            get
            {
                return this.refrenceField;
            }
            set
            {
                this.refrenceField = value;
            }
        }

        public decimal Amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AmountSpecified
        {
            get
            {
                return this.amountFieldSpecified;
            }
            set
            {
                this.amountFieldSpecified = value;
            }
        }
    }

    public enum TransactionType
    {

        /// <remarks/>
        Order,

        /// <remarks/>
        Payment,

        /// <remarks/>
        Commission,

        /// <remarks/>
        Delivery,
    }
}
